simulation_rate: 100.0
clock_rate: 100.0
realtime_factor: 1.0

iterate_without_input: true

individual_takeoff_platform:
  enabled: false

collisions:
  enabled: true
  crash: false

  # if crash==false, then the collisions are elastic
  rebounce: 100.0

# randomization of the initial conditions around the desired spawn point
randomization:

  enabled: true

  bounds:
    x: 15.0
    y: 15.0
    z: 15.0

ground:
  enabled: true
  z: 0.0 # [m]

uav_names: [
  "uav1",
  "uav2",
  "uav3",
]

uav1:
  type: "x500"
  spawn:
    x: 0.0
    y: 0.0
    z: 2.0
    heading: 0

uav2:
  type: "x500"
  spawn:
    x: 4.0
    y: 0.0
    z: 2.0
    heading: 0

uav3:
  type: "x500"
  spawn:
    x: 8.0
    y: 0.0
    z: 2.0
    heading: 0
